export const suggestedCourses = [
  {
    _id: '66b74da8cc64a0695c92417f',
    title: 'Ghép ảnh chuyên nghiệp với Photoshop',
    oldPrice: 299000,
    price: 79000,
    citing: 'unica.vn',
    author: 'Huy Quần Hoa',
    textHook:
      'Học ghép ảnh, thiết kế ảnh đẹp, hấp dẫn, thỏa sức ghép ảnh với thần tượng hay xuất hiện trong các bộ phim nổi tiếng Hollywood. Khoá học sẽ hướng dẫn chi tiết bạn cách cắt ghép cách blend màu và ánh sáng, tạo bóng sao cho bức ảnh trông thật nhất và chuyên nghiệp thỏa sức đam mê ghép hình.',
    description:
      '<h4 class="undefined text-xl font-semibold">Bạn sẽ học những gì?</h4><ol class="list-decimal px-[1rem] mr-[1rem] ml-[0.4rem]"><li class="my-[0.25em]"><p>Sử dụng thành thạo phần mềm học&nbsp;ghép ảnh chuyên nghiệp với Photoshop</p></li><li class="my-[0.25em]"><p>Học cách cắt ghép ảnh&nbsp;và lên ý tưởng cho một&nbsp;tấm hình</p></li><li class="my-[0.25em]"><p>Nắm được quy tắc hướng sáng cũng như bố cục của một&nbsp;bức ảnh</p></li><li class="my-[0.25em]"><p>Biết cách Retouch và Blend màu cho bất kỳ&nbsp;tấm ảnh nào</p></li><li class="my-[0.25em]"><p>Tự ghép bản thân mình vào trong các phim ảnh hay đứng chụp cùng thần tượng một&nbsp;cách chân thật</p></li><li class="my-[0.25em]"><p>Tự tin với tài năng photoshop của bản thân, thỏa sức sáng tạo cùng photoshop</p></li></ol><p></p><p>Photoshop tên đầy đủ là Adobe Photoshop hay PS là một trong những phần mềm mang đến nhiều phép màu và sự ảo diệu nhất trong cuộc sống.</p><p style="text-align: justify">Nhắc đến Photoshop thì chúng ta không thể không nhắc đến những công dụng tuyệt vời của nó đem lại cho người sử dụng phần mềm.</p><p style="text-align: justify">✔️ <strong>Thiết kế</strong></p><p style="text-align: justify">Photoshop là một trong những nhu cầu của đại đa số các cá nhân theo học Photoshop, nó giúp cho bạn học thiết kế&nbsp;được banner, thiết kế quảng cáo, icon, apps, ảnh 3D một cách dễ dàng.</p><p style="text-align: justify">✔️ <strong>Xử lý hình ảnh</strong></p><p style="text-align: justify">Bạn sử dụng thành thạo Photoshop thì sẽ thỏa sức sáng tạo không giới hạn từ đơn giản đến phức tạp những bức ảnh thần thánh có “1 không 2”.</p><p style="text-align: justify">✔️ <strong>Phục chế ảnh cũ</strong></p><p style="text-align: justify">Bạn đang có những bức ảnh cũ thì chỉ cần qua phềm mềm Photoshop thì sẽ &nbsp;được phục chế lại một cách sắc nét, rõ hơn.</p><p style="text-align: justify">✔️ <strong>Ghép ảnh</strong></p><p style="text-align: justify">Học ghép ảnh được xem là một trong những công dụng mà Photoshop đem lại cho người sử dụng. Bạn có thể&nbsp;ghép ảnh cùng thần tượng chuyên nghiệp như thật</p><p style="text-align: justify"></p><p style="text-align: justify"><strong>Tuy nhiên:</strong></p><p style="text-align: justify">❌ Bạn thiết kế ảnh quá xấu?</p><p style="text-align: justify">❌ Bạn luôn tự hỏi tại sao mình phối màu xấu đến vậy?</p><p style="text-align: justify">❌ Bạn nghèo nàn về kho tàng màu sắc và trí tưởng tượng thiết kế cho riêng mình?</p><p style="text-align: justify">❌ Bạn muốn ghép ảnh chuyên nghiệp trên Photoshop, để thỏa sức tách ghép bất cứ hình ảnh nào?</p><p style="text-align: justify">❌ Hay bạn đang hâm mộ một ai đó, muốn chụp hình cùng thần tượng của mình nhưng không có cơ hội, hay bạn ước mơ bản thân mình có trải nghiệm được xuất hiện trong các bộ phim nổi tiếng của Hollywood,...</p><p style="text-align: justify">Giải quyết hết những vấn đề trên thì bạn hãy đến với khóa học<strong> Ghép ảnh chuyên nghiệp với Photoshop</strong>&nbsp;của Mai Xuân Huy Photoshop&nbsp;(Huy Quần Hoa) sẽ giúp bạn thực hiện hóa giấc mơ qua hình ảnh. Bạn sẽ thấy thích thú khi ngắm nhìn mình trong những bức ảnh chụp cùng người nổi tiếng.</p><p style="text-align: justify">Bạn sẽ được hướng dẫn cách ghép ảnh, thiết kế ảnh đẹp, hấp dẫn, cách phối màu sắc, tách ghép chủ thể, ghép ảnh với thần tượng,&nbsp;các thủ thuật tạo bóng và ánh sáng sao cho thật nhất, giúp bạn tự tin hơn với khả năng photoshop của bản thân.</p>',
    tags: [
      {
        _id: '66ab994c255be47bd98d83d2',
        title: 'Content',
        courseQuantity: 109,
        booted: false,
        createdAt: '2024-08-01T14:18:52.851Z',
        updatedAt: '2024-10-10T07:24:17.824Z',
        slug: 'content',
        __v: 0,
      },
    ],
    category: {
      _id: '66b719a70c908a24a794f795',
      parentId: '66b719610c908a24a794f780',
      title: 'Adobe Photoshop',
      description: '',
      slug: 'thiet-ke/cong-cu-thiet-ke/adobe-photoshop',
      courseQuantity: 10,
      booted: false,
      createdAt: '2024-08-10T07:41:27.432Z',
      updatedAt: '2024-10-10T07:24:17.824Z',
      __v: 0,
      titleNoDiacritics: 'Adobe Photoshop',
    },
    images: [
      'https://d141vgbk8gzs0o.cloudfront.net/images/40b7a0f6cba9e54e8a8753c928c6e1407f90d46ae6d11722cad035ad0aa75196',
      'https://d141vgbk8gzs0o.cloudfront.net/images/19564a855b5a976c233efbeebfa9acb636c9457d314f6d6027143d7301091820',
    ],
    joined: 12468,
    active: true,
    likes: [],
    languages: ['Vietnamese'],
    booted: true,
    createdAt: '2024-08-10T11:23:20.606Z',
    updatedAt: '2024-10-10T07:07:29.323Z',
    slug: 'ghep-anh-chuyen-nghiep-voi-photoshop',
    __v: 0,
    duration: 26159,
    titleNoDiacritics: 'Ghep anh chuyen nghiep voi Photoshop',
    flashSale: {
      _id: '66ebb83452af9f797813ead8',
      type: 'percentage',
      value: '-10%',
      begin: '2024-09-19T00:00:00.000Z',
      timeType: 'loop',
      duration: 2880,
      expire: null,
      courseQuantity: 0,
      createdAt: '2024-09-19T05:35:48.672Z',
      updatedAt: '2024-09-30T03:59:33.445Z',
      __v: 0,
    },
  },
  {
    _id: '66b726782e90ed447412ca2e',
    title: 'Cắt Ghép Banner, Poster Bằng Photoshop – Huy Quần Hoa',
    oldPrice: 299000,
    price: 49000,
    citing: 'unica.vn',
    author: 'Huy Quần Hoa',
    textHook:
      'Khóa học của Huy Quần Hoa giúp bạn tự tay tạo nên những banner, poster sản phẩm đơn giản mà bắt mắt, ấn tượng mà không cần phải qua bất cứ lớp học thiết kế chuyên nghiệp nào\r\n',
    description:
      '<h4 class="undefined text-xl font-semibold">Bạn sẽ học được</h4><ol class="list-decimal px-[1rem] mr-[1rem] ml-[0.4rem]"><li class="my-[0.25em]"><p>Nắm được những kiến thức và tư duy thiết kế banner, poster cơ bản</p></li><li class="my-[0.25em]"><p>Tự thiết kết banner cho cá nhân , doanh nghiệp .</p></li><li class="my-[0.25em]"><p>Tự làm poster cho sản phẩm .</p></li><li class="my-[0.25em]"><p>Nắm được bố cục trong design banner poster.</p></li><li class="my-[0.25em]"><p>Nắm được bí quyết chọn màu phù hợp trong thiết kế</p></li><li class="my-[0.25em]"><p>Tự tin tạo nên những banner, poster mới lạ hơn mang dấu ấn của bản thân hoặc vạch ra định hướng nghề thiết kế tự do trong tương lai</p></li></ol><p></p><p><strong><u>Tầm quan trọng của Photoshop</u></strong></p><p style="text-align: justify">Thời đại công nghệ phát triển, bất cứ nghành nghề dịch vụ nào cũng cần phải có cho mình những bộ mặt thương hiệu trên các kênh truyền thông hay trang cá nhân thật bắt mắt và chuyên nghiệp, có như thế bạn mới thu hút được khách hàng, vì thế mà design là một ngành không thể thiếu trong mọi lĩnh vực hiện nay .</p><ul class="list-disc px-[1rem] mr-[1rem] ml-[0.4rem]"><li class="my-[0.25em]"><p>Bạn không biết cách tạo cho mình hay doanh nghiệp của mình một poster chuyên nghiệp?</p></li><li class="my-[0.25em]"><p>Bạn không biết cách sắp xếp bố cục sao cho phù hợp với một banner?&nbsp;</p></li><li class="my-[0.25em]"><p>Bạn không biết làm sao để hình ảnh sản phẩm trông nổi bật và có chiều sâu?</p></li><li class="my-[0.25em]"><p>Bạn không biết trang trí text làm sao cho phong phú?</p></li><li class="my-[0.25em]"><p>Bạn lo ngại bản thân không có một chút \'hoa tay\' nghệ thuật nào sẽ không thể làm được?</p><p></p></li></ul><p style="text-align: justify">Vậy thì bạn không nên bỏ qua khóa học&nbsp;"<strong>CẮT GHÉP BANNER , POSTER SẢN PHẨM ĐƠN GIẢN BẰNG PHOTOSHOP"</strong> này để nhanh chóng xây dựng cho doanh nghiệp của mình những sản phẩm truyền thông hấp dẫn, ấn tượng và chuyên nghiệp.</p><p style="text-align: justify">Khóa học thiết kế&nbsp;"<strong>CẮT GHÉP BANNER , POSTER SẢN PHẨM ĐƠN GIẢN BẰNG PHOTOSHOP"&nbsp;</strong>sẽ giúp bạn giải quyết các vấn đề trên. Trong khóa học, các bạn sẽ được giảng viên <strong>Mai Xuân Huy (Huy Quần Hoa)&nbsp;</strong>chia sẻ và hướng dẫn học viên các kiến thức từ lý thuyết tới các bài học thiết kế, kết hợp với các kỹ thuật Photoshop ấn tượng giúp học viên nhanh chóng nắm vững kiến thức và thành thạo việc tạo nên những banner, poster đơn giản mà không kém phần bắt mắt. Đồng thời còn sở hữu những tư duy thiết kế mới lạ để học viên sớm tự trải nghiệm và có thêm nhiều sản phẩm banner poster hấp dẫn khác.</p>',
    tags: [
      {
        _id: '66ab994c255be47bd98d83d2',
        title: 'Content',
        courseQuantity: 109,
        booted: false,
        createdAt: '2024-08-01T14:18:52.851Z',
        updatedAt: '2024-10-10T07:24:17.824Z',
        slug: 'content',
        __v: 0,
      },
    ],
    category: {
      _id: '66b719a70c908a24a794f795',
      parentId: '66b719610c908a24a794f780',
      title: 'Adobe Photoshop',
      description: '',
      slug: 'thiet-ke/cong-cu-thiet-ke/adobe-photoshop',
      courseQuantity: 10,
      booted: false,
      createdAt: '2024-08-10T07:41:27.432Z',
      updatedAt: '2024-10-10T07:24:17.824Z',
      __v: 0,
      titleNoDiacritics: 'Adobe Photoshop',
    },
    images: [
      'https://d141vgbk8gzs0o.cloudfront.net/images/fdc6dbc0af821c331800017248b24b2700242ccd69ae9edfadc2f0cdec37e00b',
      'https://d141vgbk8gzs0o.cloudfront.net/images/952cee632906eee38152921678b3e8dd2ca4fa2261aeb05522caa6ad05176f8c',
    ],
    joined: 10670,
    active: true,
    likes: [],
    languages: ['Vietnamese'],
    booted: true,
    createdAt: '2024-08-10T08:36:08.256Z',
    updatedAt: '2024-10-10T07:07:41.147Z',
    slug: 'cat-ghep-banner-poster-bang-photoshop-huy-quan-hoa',
    __v: 0,
    duration: 27553,
    titleNoDiacritics: 'Cat Ghep Banner, Poster Bang Photoshop – Huy Quan Hoa',
    flashSale: {
      _id: '66ebb83452af9f797813ead8',
      type: 'percentage',
      value: '-10%',
      begin: '2024-09-19T00:00:00.000Z',
      timeType: 'loop',
      duration: 2880,
      expire: null,
      courseQuantity: 0,
      createdAt: '2024-09-19T05:35:48.672Z',
      updatedAt: '2024-09-30T03:59:33.445Z',
      __v: 0,
    },
  },
  {
    _id: '66b76566f3e3a93ccfc81874',
    title: 'Làm chủ photoshop cùng Huy Quần Hoa',
    oldPrice: 700000,
    price: 119000,
    citing: 'unica.vn',
    author: 'Huy Quần Hoa',
    textHook:
      'Khóa học sẽ giúp bạn bổ sung kiến thức về photoshop một cách bài bản theo lộ trình, dễ học và hiệu quả, kèm theo đó là những mẹo hữu ích, những kỹ năng độc đáo về ghép ảnh và chỉnh sửa hình ảnh\r\n',
    description:
      '<p><strong>Bạn sẽ học được</strong></p><p>Thành thạo kỹ năng ghép và chỉnh sửa ảnh bằng Photoshop</p><p>Tự thiết kế hình ảnh cho website, Fanpage facebook, Group</p><p>Cắt ghép ảnh cùng các idol yêu thích</p><p>Thỏa sức sáng tạo hình ảnh, tự thực hiện các ý tưởng của bạn qua hình ảnh cùng Photoshop</p>',
    tags: [
      {
        _id: '66ab994c255be47bd98d83d2',
        title: 'Content',
        courseQuantity: 109,
        booted: false,
        createdAt: '2024-08-01T14:18:52.851Z',
        updatedAt: '2024-10-10T07:24:17.824Z',
        slug: 'content',
        __v: 0,
      },
    ],
    category: {
      _id: '66b719a70c908a24a794f795',
      parentId: '66b719610c908a24a794f780',
      title: 'Adobe Photoshop',
      description: '',
      slug: 'thiet-ke/cong-cu-thiet-ke/adobe-photoshop',
      courseQuantity: 10,
      booted: false,
      createdAt: '2024-08-10T07:41:27.432Z',
      updatedAt: '2024-10-10T07:24:17.824Z',
      __v: 0,
      titleNoDiacritics: 'Adobe Photoshop',
    },
    images: [
      'https://d141vgbk8gzs0o.cloudfront.net/images/482ee15ebba7ee6153175bd20d156e750a5dab8bdaac30a8b17b5da51c0be5e6',
      'https://d141vgbk8gzs0o.cloudfront.net/images/cb9e51835c5e3fbfbc56146363524bad487653af79f4e9363f9584190c446b21',
    ],
    joined: 10557,
    active: true,
    likes: [],
    languages: ['Vietnamese'],
    booted: false,
    createdAt: '2024-08-10T13:04:38.695Z',
    updatedAt: '2024-10-10T07:09:16.906Z',
    slug: 'lam-chu-photoshop-cung-huy-quan-hoa',
    __v: 0,
    duration: 28582,
    titleNoDiacritics: 'Lam chu photoshop cung Huy Quan Hoa',
    flashSale: {
      _id: '66ebb83452af9f797813ead8',
      type: 'percentage',
      value: '-10%',
      begin: '2024-09-19T00:00:00.000Z',
      timeType: 'loop',
      duration: 2880,
      expire: null,
      courseQuantity: 0,
      createdAt: '2024-09-19T05:35:48.672Z',
      updatedAt: '2024-09-30T03:59:33.445Z',
      __v: 0,
    },
  },
]
